version: "3"
services:
  mysql:
    # 可以使用其他的镜像
    image: mysql:5.7
    environment:
      # 一下配置可以根据情况自行修改
      # root 用户的密码
      MYSQL_ROOT_PASSWORD: "root"
      # 要创建的数据库
      MYSQL_DATABASE: "test"
      # 用户
      MYSQL_USER: "app"
      # 密码
      MYSQL_PASSWORD: "123456"
    # 数据卷的映射关系，将数据卷保存在本地
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    # 端口映射
    ports:
      - "3306:3306"
    networks:
      app_net:
      # 固定子网ip，网段必须在子网络10.10.*.*
        ipv4_address: 10.10.10.1
    container_name: "compose-mysql"
  php:
    build: 
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./code:/www/html/app
      - ./services/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9000:9000"
    environment:
      XDEBUG_CONFIG: "remote_host=${HOST_IP}"
    env_file:
      - '.env'
    networks:
      - app_net
    container_name: "compose-php"
  nginx:
    image: nginx:1.15.2
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
      - ./services/nginx/logs:/etc/nginx/logs
      - ./code:/www/html/app
    env_file:
      - '.env'
    networks:
      - app_net
      # 容器名称
    container_name: "compose-nginx"
networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16