version: "3"
services:
  
  php:
    build: 
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./code:/www/html/app
      - ./services/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9000:9000"
    environment:
      XDEBUG_CONFIG: "remote_host=${HOST_IP}"
    env_file:
      - '.env'
  nginx:
    image: nginx:1.15.2
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
      - ./services/nginx/logs:/etc/nginx/logs
      - ./code:/www/html/app
    env_file:
      - '.env'